# Generated by Django 2.2 on 2019-05-03 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('civil_registry', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changeset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('change', models.IntegerField(choices=[(1, 'Move voters to another polling center'), (2, 'Block voters'), (3, 'Unblock voters'), (4, 'Roll back another changeset')], default=1, verbose_name='change')),
                ('how_to_select', models.IntegerField(choices=[(1, 'Select a list of polling centers'), (2, 'Upload a list of national IDs'), (3, 'Select another changeset')], default=1, help_text='How to select affected voters. If you select another changeset, it will change the same voters who were changed in the other changeset, which might NOT be the same as using the same rules for selecting voters that the other changeset used.', verbose_name='how to select')),
                ('message', models.CharField(blank=True, default='', help_text='Optional text message to send to affected voters after applying change', max_length=1024, verbose_name='message')),
                ('justification', models.TextField(help_text='Reason for the changes. Include references to legal justification for the changes if possible.', verbose_name='justification')),
                ('execution_start_time', models.DateTimeField(blank=True, editable=False, help_text='When execution of the changeset started.', null=True, verbose_name='start time')),
                ('finish_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='finish time')),
                ('status', models.IntegerField(choices=[(1, 'New - not approved'), (2, 'Approved - not started'), (3, 'Started - start button has been pressed but processing has not begun'), (4, 'Executing - being processed'), (5, 'Failed - had errors, changes were not made'), (6, 'Successful - completed without errors and not rolled back'), (7, 'Partially successful - rollback was not able to rollback all changes'), (8, 'Rolled back - some or all changes have been rolled back')], default=1, verbose_name='status')),
                ('error_text', models.TextField(blank=True, default='', help_text='If the changes failed, this will contain the error message(s).', verbose_name='error text')),
                ('approvers', models.ManyToManyField(related_name='changeset_approvals', to=settings.AUTH_USER_MODEL, verbose_name='approvers')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changesets_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('other_changeset', models.ForeignKey(blank=True, help_text='Another changeset to select voters from or to roll back.', limit_choices_to={'status__in': [6, 7, 5, 8]}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_changesets', to='changesets.Changeset', verbose_name='other changeset')),
                ('queued_by', models.ForeignKey(blank=True, help_text='The user who queued the changeset for execution.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changesets_queued', to=settings.AUTH_USER_MODEL, verbose_name='queued by')),
                ('rollback_changeset', models.ForeignKey(blank=True, help_text='If this changeset has been rolled back, this is the changeset that did it.', null=True, on_delete=django.db.models.deletion.PROTECT, to='changesets.Changeset', verbose_name='rollback changeset')),
                ('selected_centers', models.ManyToManyField(blank=True, limit_choices_to={'deleted': False}, related_name='changesets_from', to='register.RegistrationCenter', verbose_name='selected centers')),
                ('selected_citizens', models.ManyToManyField(blank=True, related_name='changesets_selected', to='civil_registry.Citizen', verbose_name='selected citizens')),
                ('target_center', models.ForeignKey(blank=True, limit_choices_to={'deleted': False, 'reg_open': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changesets_to', to='register.RegistrationCenter', verbose_name='target center')),
            ],
            options={
                'verbose_name': 'changeset',
                'verbose_name_plural': 'changesets',
                'ordering': ['-creation_date'],
                'permissions': [('approve_changeset', 'Approve changeset'), ('queue_changeset', 'Start changeset'), ('browse_changeset', 'Browse changesets'), ('read_changeset', 'Read changeset')],
            },
        ),
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('changed', models.BooleanField(default=True, help_text='Whether change was made', verbose_name='changed')),
                ('change', models.IntegerField(choices=[(1, 'Move voters to another polling center'), (2, 'Block voters'), (3, 'Unblock voters'), (4, 'Roll back another changeset')], verbose_name='change')),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_records', to='changesets.Changeset', verbose_name='changeset')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_records', to='civil_registry.Citizen', verbose_name='citizen')),
                ('from_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes_made_from', to='register.RegistrationCenter', verbose_name='from center')),
                ('to_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes_made_to', to='register.RegistrationCenter', verbose_name='to center')),
            ],
            options={
                'verbose_name': 'change record',
                'verbose_name_plural': 'change records',
                'ordering': ['change', 'changeset_id', 'citizen_id'],
                'permissions': [('browse_changerecord', 'Browse changerecords')],
                'unique_together': {('changeset', 'citizen')},
            },
        ),
    ]
