# Generated by Django 2.2 on 2019-05-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='report')),
                ('hq_reports', models.TextField(verbose_name='headquarters reports')),
                ('message_log', models.TextField(verbose_name='message log')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.Election', verbose_name='election')),
            ],
            options={
                'verbose_name': 'election report',
                'verbose_name_plural': 'election reports',
            },
        ),
    ]
