# Generated by Django 2.2 on 2019-05-03 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import libya_elections.libya_bread


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VumiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('uuid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='uuid')),
                ('logged_date', models.DateTimeField(blank=True, null=True, verbose_name='logged date')),
                ('direction', models.IntegerField(choices=[(1, 'Incoming'), (2, 'Outgoing')], verbose_name='direction')),
                ('to_addr', models.CharField(blank=True, max_length=255, verbose_name='to address')),
                ('from_addr', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('is_audited', models.BooleanField(db_index=True, default=False, verbose_name='is audited')),
                ('raw_text', models.TextField(blank=True, verbose_name='raw text')),
            ],
            options={
                'verbose_name': 'vumi log',
                'verbose_name_plural': 'vumi logs',
                'ordering': ['-creation_date'],
                'permissions': [('read_vumilog', 'Read vumilog records')],
            },
        ),
        migrations.CreateModel(
            name='SMSTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('sms', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.SMS', verbose_name='sms')),
                ('vumi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.VumiLog', verbose_name='vumi log')),
            ],
            options={
                'verbose_name': 'sms trail',
                'verbose_name_plural': 'sms trails',
            },
            bases=(libya_elections.libya_bread.SMSFormatterMixin, libya_elections.libya_bread.VumilogFormatterMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('trail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audit.SMSTrail', verbose_name='sms trail')),
            ],
            options={
                'verbose_name': 'sms discrepancy',
                'verbose_name_plural': 'sms discrepancies',
                'ordering': ['-creation_date'],
                'permissions': [('browse_discrepancy', 'Browse discrepancies'), ('read_discrepancy', 'Read discrepancy')],
            },
        ),
    ]
