# Generated by Django 2.2 on 2019-05-03 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import libya_elections.libya_bread


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
        ('voting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('gender', models.PositiveSmallIntegerField(verbose_name='gender')),
                ('n_registrants', models.IntegerField(verbose_name='number of registrants')),
                ('first_voter_name', models.CharField(max_length=255, verbose_name='first voter name')),
                ('first_voter_number', models.IntegerField(verbose_name='first voter number')),
                ('last_voter_name', models.CharField(max_length=255, verbose_name='last voter name')),
                ('last_voter_number', models.IntegerField(verbose_name='last voter number')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.RegistrationCenter', verbose_name='registration center')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Election', verbose_name='election')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
                'ordering': ('center__center_id', 'number'),
                'permissions': [('browse_station', 'Can list stations'), ('read_station', 'Can read a station')],
                'unique_together': {('election', 'center', 'number')},
            },
            bases=(libya_elections.libya_bread.ElectionFormatterMixin, libya_elections.libya_bread.RegistrationCenterFormatterMixin, models.Model),
        ),
    ]
