# Generated by Django 2.2 on 2019-05-03 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('subscription_type', models.IntegerField(choices=[(1, 'SMS Discrepancies')], default=1, verbose_name='subscription type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email alert subscription',
                'verbose_name_plural': 'email alert subscriptions',
                'permissions': [('browse_subscription', 'Browse subscriptions'), ('read_subscription', 'Read subscriptions')],
                'unique_together': {('user', 'subscription_type')},
            },
        ),
    ]
