# Generated by Django 2.2 on 2019-05-03 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modification date')),
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='number')),
                ('label', models.CharField(max_length=80, verbose_name='label')),
                ('msg_en', models.TextField(max_length=512, verbose_name='english')),
                ('msg_ar', models.TextField(max_length=512, verbose_name='arabic')),
                ('enhanced_en', models.TextField(blank=True, default='', max_length=512, verbose_name='english repeat message')),
                ('enhanced_ar', models.TextField(blank=True, default='', max_length=512, verbose_name='arabic repeat message')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'message text',
                'verbose_name_plural': 'message texts',
                'ordering': ['number'],
            },
        ),
    ]
